leader1.enabled: true
leader2.enabled: false
leader3.enabled: false
leader4.enabled: false

logging.level.com.transferwise.common.leaderselector: DEBUG

tw-curator:
  zookeeper-connect-string: localhost:2281
  
---

spring:
  profiles: node1

server:
  port:
    11223

---

spring:
  profiles: node2

server:
  port:
    11224
